/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronCollectRouteImport } from './routes/api/public/cron-collect'
import { Route as ApiPublicHooksEnrichWorkerRouteImport } from './routes/api/public/hooks/enrich-worker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCollectRoute = ApiPublicCronCollectRouteImport.update({
  id: '/api/public/cron-collect',
  path: '/api/public/cron-collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEnrichWorkerRoute =
  ApiPublicHooksEnrichWorkerRouteImport.update({
    id: '/api/public/hooks/enrich-worker',
    path: '/api/public/hooks/enrich-worker',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron-collect': typeof ApiPublicCronCollectRoute
  '/api/public/hooks/enrich-worker': typeof ApiPublicHooksEnrichWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron-collect': typeof ApiPublicCronCollectRoute
  '/api/public/hooks/enrich-worker': typeof ApiPublicHooksEnrichWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron-collect': typeof ApiPublicCronCollectRoute
  '/api/public/hooks/enrich-worker': typeof ApiPublicHooksEnrichWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/cron-collect'
    | '/api/public/hooks/enrich-worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cron-collect' | '/api/public/hooks/enrich-worker'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron-collect'
    | '/api/public/hooks/enrich-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronCollectRoute: typeof ApiPublicCronCollectRoute
  ApiPublicHooksEnrichWorkerRoute: typeof ApiPublicHooksEnrichWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-collect': {
      id: '/api/public/cron-collect'
      path: '/api/public/cron-collect'
      fullPath: '/api/public/cron-collect'
      preLoaderRoute: typeof ApiPublicCronCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enrich-worker': {
      id: '/api/public/hooks/enrich-worker'
      path: '/api/public/hooks/enrich-worker'
      fullPath: '/api/public/hooks/enrich-worker'
      preLoaderRoute: typeof ApiPublicHooksEnrichWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronCollectRoute: ApiPublicCronCollectRoute,
  ApiPublicHooksEnrichWorkerRoute: ApiPublicHooksEnrichWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
